SELECT INIT(ID)
FROM STUDNET 
WHERE DEPTNO = 201;
SELECT * FROM STUDENT;

SELECT NAME, LOWER(ID), UPPER(ID) 
FROM student 
WHERE deptno1 = 201;

SELECT NAME 이름, ID, LENGTH(ID) 글자수
FROM STUDENT
WHERE LENGTH(ID) > 9;